### ISSUE TITLE
applyJsonFilter missing from MockIVisualHost

### ISSUE THREAD

**Issue by DiaAzul** [Microsoft/powerbi-visuals-utils-testutils#17]
I believe that applyJsonFilter() method is missing from MockIVisualHost in release 1.0.2 (and before).

**Comment by ignatvilesov** [comment]
You're correct. This library support API 1.6.0.
This library will be updated to support API 1.10.

**Comment by ignatvilesov** [comment]
Related to #12 as well

**Comment by ignatvilesov** [comment]
Interfaces have been extended to support `applyJsonFilter`
