### ISSUE TITLE
typings install issue

### ISSUE THREAD

**Issue by dillondanielson** [Microsoft/powerbi-visuals-utils-testutils#9]
i ran the following command and got a warning or error. I wanted to see if this was correct or if i need to update. 
`...>typings install --save --global dt~d3#0.0.0+20160907005744 dt~jasmine#2.5.0+20161025102649 dt~jasmine-jquery#0.0.0+20160317120654 dt~jquery#1.10.0+2016092916
2922 dt~lodash#4.14.0+20161028154038

typings WARN deprecated 5/9/2016: "registry:dt/jasmine-jquery#0.0.0+20160317120654" is deprecated (updated, replaced or removed)

typings WARN deprecated 11/10/2016: "registry:dt/lodash#4.14.0+20161028154038" is deprecated (updated, replaced or removed)

typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/jasmine/jasmine.d.ts" during installation
 from "jasmine-jquery" (main)

typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/jquery/jquery.d.ts" during installation f
rom "jasmine-jquery" (main)

d3
`-- (No dependencies)

jasmine
`-- (No dependencies)

jasmine-jquery
`-- (No dependencies)

jquery
`-- (No dependencies)

lodash
`-- (No dependencies)`

**Comment by ignatvilesov** [comment]
Hello @dillondanielson 

This warning is expected. Please ignore it.
We'll be able to resolve this soon.
